exclude: json/
repos:
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: markdownlint
        stages: [commit]
    -   id: shellcheck
        stages: [commit]
    -   id: shfmt
        stages: [commit]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: main
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]