exclude: json/
repos:
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: markdownlint
    -   id: shellcheck
    -   id: shfmt
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: main
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]