repos:
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: markdownlint
        stages: [commit]
        files: ".*.md"
    -   id: shellcheck
        stages: [commit]
        files: ".*.sh"
        args: [--exclude=SC1117]
    # -   id: shfmt
    #     stages: [commit]
        
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: main
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]